stages:
    - build
    - prepare
    - deploy

.workaround-off: &workaround-off
- sed -i '/-fno-pie/s/^C/#/' Makefile.housekeeping
.workaround-on: &workaround-on
- sed -i '/-fno-pie/s/^#//' Makefile.housekeeping

prepare:docs:
    image: busybox:musl
    stage: prepare
    variables:
        GIT_DEPTH: '1'
    before_script:
        - mkdir -p docs
        - mkdir -p alpine
    dependencies: []
    script:
        - mv -vf certs/ssh_key alpine/
        - mv -vf scripts/boot.ipxe alpine/
    artifacts:
        name: docs
        paths:
            - docs/*
            - alpine/ssh_key
            - alpine/boot.ipxe
        expire_in: 5 hrs
    only:
        - alpine

prepare:netboot:
    image: alpine:latest
    stage: prepare
    variables:
        GIT_DEPTH: '1'
        VERSION: '3.12.0'
    before_script:
        - apk add --no-cache openssl
        - mkdir -p alpine/netboot-${VERSION}/
    dependencies: []
    script:
        - mv -vf netboot/${VERSION}/* alpine/netboot-${VERSION}/
        - find alpine/netboot-${VERSION} -name *-lts -type f -exec openssl cms -sign -binary -noattr -in "{}" -signer certs/codesign-full.pem -inkey ${KEY} -certfile certs/rootCA.pem -outform DER -out "{}.sig" \;
    after_script:
        - find alpine/netboot-${VERSION} -name *-lts -type f -exec echo -n "{} - " \; openssl smime -verify -purpose any -in "{}.sig" -CAfile certs/codesign-full.pem -inform DER -content "{}" -out /dev/null \;
    artifacts:
        name: netboot-${VERSION}
        paths:
            - alpine/netboot-${VERSION}/*
        expire_in: 5 hrs
    only:
        - alpine

.buildtemplate:
    # see https://hub.docker.com/_/gcc/
    image: gcc:9
    stage: build
    variables:
        EMBEDSCRIPT: myscript
        GIT_DEPTH: '1'
    before_script:
        #- apk add --no-cache xz-dev binutils-dev syslinux build-base perl mtools make xorriso
        - apt update && apt -y install build-essential binutils-dev liblzma-dev syslinux 
        - gcc --version
        - mkdir -p artifacts
        - mkdir -p src/config/local
        - cp scripts/${EMBEDSCRIPT} src/
        - cp certs/{vanaware.github.io.pem,ipxe_ca.pem,codesign-full.pem} src/
    script:
        - cd src
        #- make -j 1 {bin-x86_64-linux,bin-i386-linux}/tests.linux EMBED=${EMBEDSCRIPT} CERT=vanaware.github.io.pem,ipxe_ca.pem,codesign-full.pem TRUST=vanaware.github.io.pem,ipxe_ca.pem,codesign-full.pem
        - *workaround-off
        - make -j 1 {bin-x86_64-efi,bin-x86_64-efi-sb}/{snponly,ipxe}.{efi,usb} EMBED=${EMBEDSCRIPT} CERT=vanaware.github.io.pem,ipxe_ca.pem,codesign-full.pem TRUST=vanaware.github.io.pem,ipxe_ca.pem,codesign-full.pem
        - *workaround-on
        - make -j 1 {bin-i386-pcbios,bin-x86_64-pcbios}/{undionly,ipxe}.{pxe,kpxe,kkpxe,usb,lkrn} EMBED=${EMBEDSCRIPT} CERT=vanaware.github.io.pem,ipxe_ca.pem,codesign-full.pem TRUST=vanaware.github.io.pem,ipxe_ca.pem,codesign-full.pem
        - tar cvzf ../artifacts/${EMBEDSCRIPT}.tar.gz {bin-x86_64-efi,bin-x86_64-efi-sb,bin-i386-pcbios,bin-x86_64-pcbios,bin-x86_64-linux,bin-i386-linux}/{undionly,snponly,ipxe,tests}.{efi,usb,linux,lkrn,pxe,kpxe,kkpxe,iso} 2>/dev/null || true
        - cd ..
        # - make bin/{undionly,ipxe}.{,k,kk}pxe EMBED=ipxescript DEBUG=undi,dhcp
    after_script:
        - tar -tvf artifacts/${EMBEDSCRIPT}.tar.gz
    artifacts:
        name: ${EMBEDSCRIPT}
        paths:
            - artifacts/${EMBEDSCRIPT}.tar.gz
        expire_in: 5 hrs
    cache:
        paths:
            - src/bin*/*.o
    only:
        - alpine

build:githubscript:
    extends: .buildtemplate
    variables:
        EMBEDSCRIPT: githubscript

build:tftpscript:
    extends: .buildtemplate
    variables:
        EMBEDSCRIPT: tftpscript

build:lanscript:
    extends: .buildtemplate
    variables:
        EMBEDSCRIPT: lanscript

build:wanscript:
    extends: .buildtemplate
    variables:
        EMBEDSCRIPT: wanscript

prepare:downloads:
    image: alpine:latest
    stage: prepare
    variables:
        GIT_STRATEGY: none
    dependencies:
        - build:githubscript
        - build:tftpscript
        - build:lanscript
        - build:wanscript
    before_script:
        - apk add --no-cache zip tar
        - ls artifacts -la
        - mkdir -p alpine
    script:
        - cd artifacts
        - zip -r ../alpine/download.zip *.tar.gz
        - tar -czvf ../alpine/download.tar.gz *.tar.gz
        - cd ..
    after_script:
        - rm -rf artifacts
    artifacts:
        name: downloads
        paths:
            - alpine/download.*
        expire_in: 5 hrs
    only:
        - alpine

deploy:
    image: alpine:latest
    stage: deploy
    variables:
        GIT_STRATEGY: none
    dependencies:
        - prepare:downloads
        - prepare:netboot
        - prepare:docs
    before_script:
        - apk add --no-cache git
        - git clone --branch=gh-pages --depth 1 ${CI_REPOSITORY_URL} gh-pages
        - cd gh-pages
        - git config user.name "${GITLAB_USER_NAME}"
        - git config user.email ${GITLAB_USER_EMAIL}
        - git config http.sslverify 'false'
        - git remote set-url --push origin https://${TOKEN}:x-oauth-basic@github.com/vanaware/ipxe.git
        - mkdir -p alpine
        - cd ..
    script:
        - (cd alpine && tar c .) | (cd gh-pages/alpine && tar xf -)
        - (cd docs && tar c .) | (cd gh-pages && tar xf -)
        - cd gh-pages
        - git add index.md
        - git add _config.yml
        - git add .gitignore
        - git add alpine/download.zip
        - git add alpine/download.tar.gz
        - git add alpine/ssh_key
        - git add alpine/boot.ipxe
        - git add alpine/netboot*
        - git commit -m "GitLab Runner Pipeline at ${CI_PIPELINE_URL}"
        - git push origin gh-pages
        - cd ..
    after_script:
        - rm -fr alpine
        - rm -fr docs
        - rm -fr gh-pages/.git
    artifacts:
        name: gh-pages
        paths:
            - gh-pages
    only:
        - alpine